// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: orbit/split/tx.proto

package split

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_UpdateParams_FullMethodName                 = "/orbit.split.Msg/UpdateParams"
	Msg_CreateSplitterPool_FullMethodName           = "/orbit.split.Msg/CreateSplitterPool"
	Msg_UpdateSplitterPoolIcaAccount_FullMethodName = "/orbit.split.Msg/UpdateSplitterPoolIcaAccount"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// CreateSplitterPool tx will create a pool which store the lsd and returns yield and principle tokens
	CreateSplitterPool(ctx context.Context, in *MsgCreateSplitterPool, opts ...grpc.CallOption) (*MsgCreateSplitterPoolResponse, error)
	// query the
	UpdateSplitterPoolIcaAccount(ctx context.Context, in *MsgUpdateplitterPoolAccount, opts ...grpc.CallOption) (*MsgUpdateplitterPoolAccountResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateSplitterPool(ctx context.Context, in *MsgCreateSplitterPool, opts ...grpc.CallOption) (*MsgCreateSplitterPoolResponse, error) {
	out := new(MsgCreateSplitterPoolResponse)
	err := c.cc.Invoke(ctx, Msg_CreateSplitterPool_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateSplitterPoolIcaAccount(ctx context.Context, in *MsgUpdateplitterPoolAccount, opts ...grpc.CallOption) (*MsgUpdateplitterPoolAccountResponse, error) {
	out := new(MsgUpdateplitterPoolAccountResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateSplitterPoolIcaAccount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// CreateSplitterPool tx will create a pool which store the lsd and returns yield and principle tokens
	CreateSplitterPool(context.Context, *MsgCreateSplitterPool) (*MsgCreateSplitterPoolResponse, error)
	// query the
	UpdateSplitterPoolIcaAccount(context.Context, *MsgUpdateplitterPoolAccount) (*MsgUpdateplitterPoolAccountResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) CreateSplitterPool(context.Context, *MsgCreateSplitterPool) (*MsgCreateSplitterPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSplitterPool not implemented")
}
func (UnimplementedMsgServer) UpdateSplitterPoolIcaAccount(context.Context, *MsgUpdateplitterPoolAccount) (*MsgUpdateplitterPoolAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSplitterPoolIcaAccount not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateSplitterPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateSplitterPool)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateSplitterPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CreateSplitterPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateSplitterPool(ctx, req.(*MsgCreateSplitterPool))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateSplitterPoolIcaAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateplitterPoolAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateSplitterPoolIcaAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateSplitterPoolIcaAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateSplitterPoolIcaAccount(ctx, req.(*MsgUpdateplitterPoolAccount))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orbit.split.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "CreateSplitterPool",
			Handler:    _Msg_CreateSplitterPool_Handler,
		},
		{
			MethodName: "UpdateSplitterPoolIcaAccount",
			Handler:    _Msg_UpdateSplitterPoolIcaAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orbit/split/tx.proto",
}
